apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  namespace: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: test/testapp:v1
        ports:
        - containerPort: 5000

